### PR TITLE
Mw/surface file status

### PR DESCRIPTION
**Pull request by michaelwood**
Addresses https://github.com/ThreeSixtyGiving/qualitydashboard/issues/9

### CODE REVIEW

**Comment by mariongalley** [comment]
@michaelwood Is there a dev branch to test this in? Or could you show me a screenshot of how it looks when a file is down?

**Review by mariongalley — APPROVED** [review]
Per our discussion, I'm happy with this

**Review by R2ZER0 — APPROVED** [review]
Looks good :+1:

**Comment by michaelwood** [comment]
deployed

**Pull request merged**
